In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
## One Hot Representation for every word
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[3750, 5103, 4373, 2278],
 [3750, 5103, 4373, 4300],
 [3750, 9138, 4373, 3549],
 [5644, 2766, 7417, 4622, 1019],
 [5644, 2766, 7417, 4622, 9328],
 [5238, 3750, 4789, 4373, 1491],
 [6781, 3873, 6716, 4622]]

In [7]:
## word embeding representation
from tensorflow.keras.layers import Embedding
## from tensorflow.keras.processing.sequence import pad_sequence
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np 

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3750 5103 4373 2278]
 [   0    0    0    0 3750 5103 4373 4300]
 [   0    0    0    0 3750 9138 4373 3549]
 [   0    0    0 5644 2766 7417 4622 1019]
 [   0    0    0 5644 2766 7417 4622 9328]
 [   0    0    0 5238 3750 4789 4373 1491]
 [   0    0    0    0 6781 3873 6716 4622]]


In [12]:
## Feature Representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\Projects\Churn_modelling\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


array([[[ 7.65497610e-03,  9.98970121e-03, -1.56905539e-02,
         -3.10747977e-02, -3.96482348e-02, -4.60896008e-02,
         -4.21245024e-03,  1.87127851e-02, -3.79177332e-02,
         -2.88814660e-02],
        [ 7.65497610e-03,  9.98970121e-03, -1.56905539e-02,
         -3.10747977e-02, -3.96482348e-02, -4.60896008e-02,
         -4.21245024e-03,  1.87127851e-02, -3.79177332e-02,
         -2.88814660e-02],
        [ 7.65497610e-03,  9.98970121e-03, -1.56905539e-02,
         -3.10747977e-02, -3.96482348e-02, -4.60896008e-02,
         -4.21245024e-03,  1.87127851e-02, -3.79177332e-02,
         -2.88814660e-02],
        [ 7.65497610e-03,  9.98970121e-03, -1.56905539e-02,
         -3.10747977e-02, -3.96482348e-02, -4.60896008e-02,
         -4.21245024e-03,  1.87127851e-02, -3.79177332e-02,
         -2.88814660e-02],
        [-4.24869657e-02,  3.61976884e-02, -3.53304036e-02,
          2.39729322e-02,  5.79730421e-03,  2.97509097e-02,
         -3.56812403e-03,  2.10608132e-02, -2.644101

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 3750, 5103, 4373, 2278])